# The Python Mega Course: Build 10 Real World Applications
---

This notebook is a summary of [The Python Mega Course: Build 10 Real World Applciations](https://www.udemy.com/the-python-mega-course), a comprehensive online Python course taught by Ardit Sulce. Each lecture name is clickable and takes you to the video lecture in the course.

# Section 15: Python for Image and Video Processing with OpenCV
***

**Lecture:** [Introduction](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775466?start=0)
---

Python can perform image processing via its OpenCV library. Image processing consists of loading images, and performing different kinds of operations on the image pixels. Such operations are converting to grayscale, blurrying, clipping, and many others. Python can process videos too since they are made of images. 

**Lecture:** [Installing the Library](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5940500?start=0)
---

OpenCV can be installed with pip:

`pip install opencv-python`

Then it can be imported as:

`import cv2`

**Lecture:** [Loading, Displaying, Resizing, and Writing Images](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775488?start=0)
---

In [ ]:
import cv2

img = cv2.imread("galaxy.jpg", 0)

print(type(img))
print(img)
print(img.shape)
print(img.ndim)

resized_image = cv2.resize(img, (int(img.shape[1]/2), int(img.shape[0]/2)))
cv2.imshow("Galaxy", resized_image)
cv2.imwrite("Galaxy_resized.jpg", resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]
(1485, 990)
2


**Practice:** [Batch Image Processing](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775490?start=0)
---

Write a script that resizes all images in a directory to 100x100. For your convenience, you can find attached a the `images` directory with some jpg images inside.

**Solution:** [Batch Image Processing](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5214910?start=0)
---

In [5]:
import cv2
import glob

images = glob.glob("images/*.jpg")
print("Input images are:", images)

for image in images:
    print("Processing", image)
    img = cv2.imread(image, 0)
    re = cv2.resize(img, (100, 100))
    cv2.imshow("Hey", re)
    cv2.waitKey(500)
    cv2.destroyAllWindows()
    cv2.imwrite("images/resized_" + image.split("/")[1], re)

Input images are: ['images/galaxy.jpg', 'images/kangaroos-rain-australia_71370_990x742.jpg', 'images/Lighthouse.jpg', 'images/Moon sinking, sun rising.jpg', 'images/resized_galaxy.jpg', 'images/resized_kangaroos-rain-australia_71370_990x742.jpg', 'images/resized_Lighthouse.jpg', 'images/resized_Moon sinking, sun rising.jpg']
Processing  images/galaxy.jpg
Processing  images/kangaroos-rain-australia_71370_990x742.jpg
Processing  images/Lighthouse.jpg
Processing  images/Moon sinking, sun rising.jpg
Processing  images/resized_galaxy.jpg
Processing  images/resized_kangaroos-rain-australia_71370_990x742.jpg
Processing  images/resized_Lighthouse.jpg
Processing  images/resized_Moon sinking, sun rising.jpg


**Solution with Explanations:** [Batch Image Processing](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775492?start=0)
---

This video lecture explains how the code of the previous lecture works.

**Lecture:** [Face Detection](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775494?start=0)
---

The following code reads the `news.jpg` image, detects faces in the image, and draws a rectangle around the detected faces.

In [ ]:
import cv2
 
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

img = cv2.imread("news.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
faces = face_cascade.detectMultiScale(gray_img, scaleFactor=1.05, minNeighbors=5)

for x, y, w, h in faces:
    img = cv2.rectangle(img, (x, y), (x + w, y + h), (0,255,0),3)

resized = cv2.resize(img, (int(img.shape[1]/3), int(img.shape[0]/3)))
 
cv2.imshow("Gray", resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Lecture:** [Capturing Video](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/4775498?start=0)
---

The following code starts your computer camera. Make sure you run it from a .py file, not from Jupyter.

In [1]:
import cv2, time

video=cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    
    print(check)
    print(frame)
    
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("Capturing",gray)

    key=cv2.waitKey(1)
    
    if key == ord('q'):
        break

video.release()
cv2.destroyAllWindows

True
[[[51 58 66]
  [51 58 66]
  [53 59 67]
  ...
  [33 39 47]
  [36 43 51]
  [39 45 53]]

 [[54 60 68]
  [54 60 68]
  [54 60 68]
  ...
  [37 44 52]
  [39 45 53]
  [39 45 53]]

 [[53 62 69]
  [53 62 69]
  [52 60 68]
  ...
  [39 45 53]
  [39 45 53]
  [39 45 53]]

 ...

 [[23 30 38]
  [25 31 39]
  [27 33 41]
  ...
  [14 19 32]
  [13 18 31]
  [ 9 14 27]]

 [[26 32 40]
  [25 31 39]
  [27 33 41]
  ...
  [15 20 33]
  [14 19 32]
  [14 19 32]]

 [[28 34 42]
  [23 30 38]
  [25 31 39]
  ...
  [13 18 31]
  [16 21 34]
  [15 20 33]]]
True
[[[101 114 123]
  [103 116 126]
  [105 117 127]
  ...
  [ 72  87  98]
  [ 71  86  97]
  [ 77  91 103]]

 [[102 115 124]
  [102 115 124]
  [103 116 126]
  ...
  [ 75  89 100]
  [ 78  93 104]
  [ 82  96 107]]

 [[102 115 124]
  [102 115 124]
  [105 117 127]
  ...
  [ 78  93 104]
  [ 79  94 105]
  [ 81  95 106]]

 ...

 [[ 62  73  83]
  [ 65  75  85]
  [ 68  79  88]
  ...
  [ 39  52  82]
  [ 37  50  79]
  [ 37  50  79]]

 [[ 64  74  84]
  [ 65  75  85]
  [ 69  80  89

True
[[[103 116 126]
  [102 115 124]
  [102 115 124]
  ...
  [ 80  93 102]
  [ 80  93 102]
  [ 79  92 101]]

 [[103 116 126]
  [101 114 123]
  [102 115 124]
  ...
  [ 80  93 102]
  [ 80  93 102]
  [ 80  93 102]]

 [[103 116 126]
  [102 115 124]
  [102 115 124]
  ...
  [ 80  93 102]
  [ 79  92 101]
  [ 80  93 102]]

 ...

 [[ 62  71  86]
  [ 62  71  86]
  [ 65  74  86]
  ...
  [ 35  48  75]
  [ 39  53  80]
  [ 40  54  81]]

 [[ 64  72  87]
  [ 62  71  86]
  [ 65  74  86]
  ...
  [ 36  49  77]
  [ 36  49  77]
  [ 37  50  78]]

 [[ 65  74  88]
  [ 65  74  88]
  [ 62  72  84]
  ...
  [ 39  53  80]
  [ 31  45  72]
  [ 31  45  72]]]
True
[[[106 117 131]
  [105 116 130]
  [103 115 129]
  ...
  [ 85  97 109]
  [ 84  96 107]
  [ 78  90 102]]

 [[106 117 131]
  [105 116 130]
  [103 115 129]
  ...
  [ 84  96 107]
  [ 83  95 106]
  [ 79  91 103]]

 [[106 117 131]
  [106 117 131]
  [105 116 130]
  ...
  [ 81  93 105]
  [ 83  95 106]
  [ 81  93 105]]

 ...

 [[ 62  71  86]
  [ 64  72  87]
  [ 66  76

True
[[[103 112 126]
  [104 113 128]
  [104 113 128]
  ...
  [ 79  93 107]
  [ 78  92 106]
  [ 78  92 106]]

 [[104 113 128]
  [103 112 126]
  [102 111 125]
  ...
  [ 79  93 107]
  [ 79  93 107]
  [ 79  93 107]]

 [[102 111 125]
  [104 113 128]
  [101 110 124]
  ...
  [ 79  93 107]
  [ 78  92 106]
  [ 78  92 106]]

 ...

 [[ 62  74  81]
  [ 62  74  81]
  [ 60  71  79]
  ...
  [ 33  47  74]
  [ 31  45  72]
  [ 36  49  77]]

 [[ 62  74  81]
  [ 62  74  81]
  [ 61  72  80]
  ...
  [ 33  47  74]
  [ 31  45  72]
  [ 35  48  75]]

 [[ 62  74  81]
  [ 62  74  81]
  [ 61  72  80]
  ...
  [ 40  54  81]
  [ 36  49  77]
  [ 33  47  74]]]
True
[[[108 117 131]
  [104 113 128]
  [101 110 124]
  ...
  [ 77  95 103]
  [ 76  94 102]
  [ 75  93 101]]

 [[107 115 130]
  [103 112 126]
  [101 110 124]
  ...
  [ 76  94 102]
  [ 79  96 105]
  [ 77  95 103]]

 [[104 113 128]
  [103 112 126]
  [102 111 125]
  ...
  [ 78  93 102]
  [ 81  96 105]
  [ 81  96 105]]

 ...

 [[ 68  79  88]
  [ 67  77  87]
  [ 65  75

True
[[[108 119 126]
  [108 119 126]
  [101 115 122]
  ...
  [ 78  93 104]
  [ 76  90 102]
  [ 78  93 104]]

 [[107 118 125]
  [107 118 125]
  [105 118 125]
  ...
  [ 79  94 105]
  [ 83  97 109]
  [ 83  97 109]]

 [[105 118 125]
  [106 119 126]
  [101 115 122]
  ...
  [ 81  95 106]
  [ 84  98 110]
  [ 82  96 107]]

 ...

 [[ 62  74  84]
  [ 62  74  84]
  [ 65  75  85]
  ...
  [ 38  48  78]
  [ 31  41  71]
  [ 32  42  72]]

 [[ 62  74  84]
  [ 63  76  85]
  [ 64  74  84]
  ...
  [ 37  47  77]
  [ 40  50  81]
  [ 39  49  79]]

 [[ 60  73  83]
  [ 60  73  83]
  [ 62  73  83]
  ...
  [ 41  52  82]
  [ 42  53  83]
  [ 40  50  81]]]
True
[[[105 117 127]
  [105 117 127]
  [101 114 123]
  ...
  [ 76  89 103]
  [ 82  95 109]
  [ 78  92 106]]

 [[106 119 128]
  [106 119 128]
  [100 113 122]
  ...
  [ 78  92 106]
  [ 81  94 108]
  [ 79  93 107]]

 [[105 117 127]
  [105 117 127]
  [101 114 123]
  ...
  [ 79  93 107]
  [ 82  95 109]
  [ 79  93 107]]

 ...

 [[ 66  74  84]
  [ 68  76  86]
  [ 67  75

True
[[[105 116 130]
  [102 114 128]
  [102 114 128]
  ...
  [ 79  93 107]
  [ 78  93 104]
  [ 77  91 103]]

 [[103 115 129]
  [102 114 128]
  [101 112 126]
  ...
  [ 81  94 108]
  [ 81  95 106]
  [ 79  94 105]]

 [[102 114 128]
  [101 112 126]
  [102 114 128]
  ...
  [ 81  95 106]
  [ 78  93 104]
  [ 79  94 105]]

 ...

 [[ 60  73  83]
  [ 63  76  85]
  [ 60  73  83]
  ...
  [ 36  52  79]
  [ 36  52  79]
  [ 34  50  77]]

 [[ 62  74  84]
  [ 62  74  84]
  [ 63  76  85]
  ...
  [ 38  54  81]
  [ 38  54  81]
  [ 36  52  79]]

 [[ 60  73  83]
  [ 63  76  85]
  [ 63  76  85]
  ...
  [ 37  53  80]
  [ 37  53  80]
  [ 38  54  81]]]
True
[[[106 116 126]
  [106 116 126]
  [102 112 122]
  ...
  [ 79  95 103]
  [ 78  93 102]
  [ 78  93 102]]

 [[104 115 124]
  [104 115 124]
  [103 114 123]
  ...
  [ 79  95 103]
  [ 79  95 103]
  [ 79  95 103]]

 [[108 116 126]
  [106 114 124]
  [105 113 123]
  ...
  [ 81  96 105]
  [ 79  95 103]
  [ 78  93 102]]

 ...

 [[ 67  75  85]
  [ 66  74  84]
  [ 66  74

True
[[[101 116 120]
  [106 120 125]
  [102 117 121]
  ...
  [ 79  94 105]
  [ 81  93 105]
  [ 83  95 106]]

 [[101 116 120]
  [103 118 122]
  [100 114 119]
  ...
  [ 82  96 107]
  [ 81  93 105]
  [ 81  93 105]]

 [[103 118 122]
  [101 116 120]
  [100 114 119]
  ...
  [ 79  94 105]
  [ 80  92 104]
  [ 79  91 103]]

 ...

 [[ 68  72  85]
  [ 64  69  82]
  [ 66  71  84]
  ...
  [ 35  50  79]
  [ 35  50  79]
  [ 35  50  79]]

 [[ 66  71  84]
  [ 64  69  82]
  [ 65  70  83]
  ...
  [ 33  48  77]
  [ 36  51  81]
  [ 36  51  81]]

 [[ 70  75  88]
  [ 66  71  84]
  [ 63  68  81]
  ...
  [ 33  48  77]
  [ 36  51  81]
  [ 34  49  78]]]
True
[[[110 117 122]
  [108 116 121]
  [108 115 123]
  ...
  [ 83  94 108]
  [ 83  94 108]
  [ 83  94 108]]

 [[111 118 124]
  [112 119 125]
  [114 121 129]
  ...
  [ 84  95 109]
  [ 83  94 108]
  [ 83  94 108]]

 [[112 118 126]
  [111 117 125]
  [115 121 131]
  ...
  [ 83  94 108]
  [ 83  94 108]
  [ 83  94 108]]

 ...

 [[ 66  72  87]
  [ 68  74  89]
  [ 62  69

True
[[[ 72  86  93]
  [ 79  93 100]
  [ 81  95 102]
  ...
  [ 64  72  84]
  [ 59  66  78]
  [ 59  66  78]]

 [[ 83  96 103]
  [ 80  94 101]
  [ 76  89  96]
  ...
  [ 63  70  83]
  [ 60  67  79]
  [ 57  65  77]]

 [[ 84  97 104]
  [ 78  92  98]
  [ 72  86  93]
  ...
  [ 61  68  81]
  [ 62  69  82]
  [ 57  65  77]]

 ...

 [[ 50  58  70]
  [ 49  56  69]
  [ 47  54  67]
  ...
  [ 30  37  63]
  [ 31  38  65]
  [ 30  37  63]]

 [[ 48  55  68]
  [ 48  55  68]
  [ 48  55  68]
  ...
  [ 29  36  62]
  [ 29  36  62]
  [ 29  36  62]]

 [[ 45  52  64]
  [ 47  54  67]
  [ 48  55  68]
  ...
  [ 28  35  61]
  [ 28  35  61]
  [ 29  36  62]]]
True
[[[ 83  88  99]
  [ 87  93 103]
  [ 90  98 108]
  ...
  [ 63  71  81]
  [ 62  70  80]
  [ 63  71  81]]

 [[ 85  91 101]
  [ 86  92 102]
  [ 77  85  95]
  ...
  [ 63  71  81]
  [ 63  71  81]
  [ 63  71  81]]

 [[ 91  96 107]
  [ 87  93 103]
  [ 74  82  92]
  ...
  [ 58  71  80]
  [ 58  71  80]
  [ 58  71  80]]

 ...

 [[ 48  56  66]
  [ 47  55  65]
  [ 43  51

True
[[[ 82  99 117]
  [ 89 106 124]
  [ 95 110 126]
  ...
  [ 78  86 101]
  [ 78  86 101]
  [ 73  82  96]]

 [[ 86 103 120]
  [ 86 103 120]
  [ 89 104 120]
  ...
  [ 73  82  96]
  [ 75  84  99]
  [ 76  85 100]]

 [[ 88 105 123]
  [ 87 104 122]
  [ 88 103 119]
  ...
  [ 71  78  93]
  [ 80  86 101]
  [ 81  87 102]]

 ...

 [[142 118 122]
  [145 121 125]
  [148 124 128]
  ...
  [ 79  78  81]
  [ 81  77  82]
  [ 84  79  85]]

 [[139 123 123]
  [140 124 124]
  [140 124 124]
  ...
  [ 78  78  78]
  [ 77  73  76]
  [ 75  72  75]]

 [[141 125 125]
  [135 119 120]
  [139 123 123]
  ...
  [ 85  85  85]
  [ 81  78  81]
  [ 75  72  75]]]
True
[[[ 92 112 127]
  [ 84 104 119]
  [ 71  91 106]
  ...
  [ 62  70  80]
  [ 62  70  80]
  [ 64  72  83]]

 [[ 88 108 123]
  [ 80 100 115]
  [ 72  92 107]
  ...
  [ 69  77  87]
  [ 67  75  85]
  [ 64  72  83]]

 [[ 86 105 123]
  [ 83 102 119]
  [ 72  91 109]
  ...
  [ 67  75  85]
  [ 68  76  86]
  [ 68  76  86]]

 ...

 [[202 163 156]
  [202 163 156]
  [201 162

True
[[[107 132 153]
  [111 136 157]
  [110 134 158]
  ...
  [ 76  88  98]
  [ 78  92  98]
  [ 77  90  97]]

 [[107 132 153]
  [111 136 157]
  [110 134 158]
  ...
  [ 77  90  99]
  [ 76  89  96]
  [ 81  95 102]]

 [[111 134 155]
  [112 135 156]
  [111 136 157]
  ...
  [ 76  88  99]
  [ 80  93 102]
  [ 80  93 102]]

 ...

 [[148 144 156]
  [148 144 156]
  [149 146 155]
  ...
  [101 105  93]
  [ 95  98  91]
  [ 92  94  87]]

 [[143 138 153]
  [144 140 154]
  [144 140 152]
  ...
  [ 93  96  87]
  [ 90  91  86]
  [ 83  84  80]]

 [[139 134 148]
  [139 134 148]
  [143 139 151]
  ...
  [ 80  84  74]
  [ 86  88  83]
  [ 83  84  80]]]
True
[[[116 139 158]
  [108 131 150]
  [107 129 150]
  ...
  [ 80  92 104]
  [ 80  92 104]
  [ 78  90 102]]

 [[118 141 160]
  [114 137 156]
  [110 132 154]
  ...
  [ 81  93 105]
  [ 80  92 104]
  [ 79  91 103]]

 [[120 138 158]
  [114 132 152]
  [116 134 156]
  ...
  [ 80  92 104]
  [ 80  92 104]
  [ 81  93 105]]

 ...

 [[146 148 157]
  [142 143 152]
  [138 140

True
[[[120 143 157]
  [121 144 158]
  [123 144 161]
  ...
  [ 88 101 110]
  [ 86  99 108]
  [ 84  97 106]]

 [[119 141 156]
  [121 144 158]
  [125 146 163]
  ...
  [ 88 101 110]
  [ 86  99 108]
  [ 85  98 107]]

 [[121 144 158]
  [124 146 161]
  [124 145 162]
  ...
  [ 87 100 109]
  [ 87 100 109]
  [ 87 100 109]]

 ...

 [[151 146 147]
  [150 145 146]
  [150 145 146]
  ...
  [148 143 130]
  [145 143 127]
  [145 143 127]]

 [[141 141 141]
  [141 141 141]
  [139 139 139]
  ...
  [136 140 128]
  [133 138 123]
  [132 136 122]]

 [[140 140 140]
  [139 139 139]
  [139 139 139]
  ...
  [122 126 114]
  [122 127 113]
  [125 129 115]]]
True
[[[119 140 152]
  [119 140 152]
  [119 140 152]
  ...
  [ 88 102 109]
  [ 88 102 109]
  [ 90 103 110]]

 [[120 141 153]
  [119 140 152]
  [119 140 152]
  ...
  [ 90 103 110]
  [ 88 102 109]
  [ 88 102 109]]

 [[122 143 156]
  [121 142 154]
  [121 142 154]
  ...
  [ 88 102 109]
  [ 86 100 107]
  [ 86 100 107]]

 ...

 [[135 132 133]
  [136 134 134]
  [141 138

True
[[[114 137 151]
  [118 140 155]
  [119 141 156]
  ...
  [ 81  95 102]
  [ 84  97 104]
  [ 81  95 102]]

 [[118 140 155]
  [119 141 156]
  [119 141 156]
  ...
  [ 86 100 107]
  [ 85  98 105]
  [ 84  97 104]]

 [[117 139 154]
  [114 137 151]
  [113 136 150]
  ...
  [ 81  95 102]
  [ 85  98 105]
  [ 81  95 102]]

 ...

 [[153 148 149]
  [150 145 146]
  [151 146 147]
  ...
  [141 143 129]
  [138 139 123]
  [133 134 118]]

 [[142 140 145]
  [137 136 141]
  [139 137 142]
  ...
  [120 124 112]
  [119 124 108]
  [119 124 108]]

 [[141 139 144]
  [141 139 144]
  [141 139 144]
  ...
  [100 104  92]
  [105 111  94]
  [104 109  92]]]
True
[[[117 139 154]
  [117 139 154]
  [117 139 154]
  ...
  [ 84  97 106]
  [ 85  98 107]
  [ 81  94 103]]

 [[116 138 153]
  [117 139 154]
  [116 138 153]
  ...
  [ 84  97 106]
  [ 83  95 105]
  [ 83  95 105]]

 [[117 139 154]
  [116 138 153]
  [116 138 153]
  ...
  [ 85  98 107]
  [ 83  95 105]
  [ 84  97 106]]

 ...

 [[150 145 146]
  [152 147 148]
  [154 149

True
[[[116 136 153]
  [116 136 153]
  [116 136 153]
  ...
  [ 85  98 107]
  [ 84  97 106]
  [ 84  97 106]]

 [[116 136 153]
  [116 136 153]
  [115 134 152]
  ...
  [ 84  97 106]
  [ 84  97 106]
  [ 84  97 106]]

 [[116 136 153]
  [118 137 154]
  [116 136 153]
  ...
  [ 84  97 106]
  [ 85  98 107]
  [ 84  97 106]]

 ...

 [[148 148 148]
  [150 150 150]
  [149 149 149]
  ...
  [139 137 122]
  [138 138 124]
  [134 135 121]]

 [[137 138 140]
  [142 144 146]
  [144 145 147]
  ...
  [118 118 112]
  [111 112 107]
  [121 123 118]]

 [[127 129 131]
  [134 136 138]
  [138 139 141]
  ...
  [102 102  95]
  [ 94  96  91]
  [ 92  94  89]]]
True
[[[116 136 151]
  [118 138 153]
  [116 136 151]
  ...
  [ 83  95 105]
  [ 83  95 105]
  [ 83  95 105]]

 [[118 138 153]
  [119 139 154]
  [118 138 153]
  ...
  [ 81  94 103]
  [ 84  97 106]
  [ 85  98 107]]

 [[119 139 154]
  [120 140 155]
  [119 139 154]
  ...
  [ 79  92 101]
  [ 79  92 101]
  [ 79  92 101]]

 ...

 [[143 141 141]
  [151 149 149]
  [148 145

True
[[[ 82  95 109]
  [ 82  95 109]
  [ 81  94 108]
  ...
  [ 50  62  74]
  [ 51  64  73]
  [ 51  64  73]]

 [[ 78  92 106]
  [ 81  94 108]
  [ 81  94 108]
  ...
  [ 46  58  70]
  [ 46  59  69]
  [ 46  59  69]]

 [[ 81  94 108]
  [ 82  95 109]
  [ 82  95 109]
  ...
  [ 48  60  71]
  [ 48  60  70]
  [ 45  58  67]]

 ...

 [[104 104 104]
  [104 104 104]
  [109 109 109]
  ...
  [ 99  99  92]
  [ 94  92  90]
  [ 99  97  95]]

 [[ 92  92  92]
  [ 95  95  95]
  [ 97  97  97]
  ...
  [ 86  87  85]
  [ 82  82  82]
  [ 84  84  84]]

 [[ 90  90  90]
  [ 92  92  92]
  [ 89  89  89]
  ...
  [ 65  66  64]
  [ 69  69  69]
  [ 65  65  65]]]
True
[[[ 75  88 102]
  [ 75  88 102]
  [ 74  87 101]
  ...
  [ 46  59  69]
  [ 44  57  66]
  [ 43  56  65]]

 [[ 75  88 102]
  [ 70  84  97]
  [ 69  82  96]
  ...
  [ 44  57  66]
  [ 46  59  69]
  [ 46  59  69]]

 [[ 69  82  96]
  [ 72  86 100]
  [ 74  87 101]
  ...
  [ 46  57  66]
  [ 48  59  69]
  [ 48  59  69]]

 ...

 [[ 92  91  94]
  [ 92  91  94]
  [ 92  91

True
[[[ 69  82  98]
  [ 69  82  98]
  [ 72  85 101]
  ...
  [ 43  51  62]
  [ 48  56  66]
  [ 50  58  69]]

 [[ 69  82  98]
  [ 70  83  99]
  [ 71  84 100]
  ...
  [ 46  54  64]
  [ 43  51  62]
  [ 43  51  62]]

 [[ 70  83  99]
  [ 70  83  99]
  [ 71  84 100]
  ...
  [ 46  54  64]
  [ 46  54  64]
  [ 43  51  62]]

 ...

 [[ 95  90  98]
  [ 94  89  97]
  [ 87  86  91]
  ...
  [ 86  87  77]
  [ 84  84  77]
  [ 77  77  70]]

 [[ 77  74  83]
  [ 78  75  84]
  [ 85  82  91]
  ...
  [ 78  80  73]
  [ 66  68  63]
  [ 68  69  64]]

 [[ 72  69  79]
  [ 75  71  81]
  [ 82  78  88]
  ...
  [ 55  57  50]
  [ 50  52  47]
  [ 58  60  55]]]
True
[[[71 82 96]
  [70 81 95]
  [71 82 96]
  ...
  [52 58 73]
  [46 52 67]
  [47 53 68]]

 [[70 81 95]
  [70 81 95]
  [71 82 96]
  ...
  [48 55 69]
  [52 58 73]
  [50 57 72]]

 [[71 82 96]
  [70 81 95]
  [71 82 96]
  ...
  [50 58 70]
  [52 59 71]
  [50 58 70]]

 ...

 [[79 77 84]
  [83 80 87]
  [85 83 90]
  ...
  [80 83 76]
  [80 82 77]
  [75 76 71]]

 [[70 63 7

True
[[[ 96 111 127]
  [ 96 111 127]
  [ 93 110 126]
  ...
  [ 63  74  88]
  [ 66  77  93]
  [ 64  74  91]]

 [[ 97 112 128]
  [ 99 115 130]
  [ 94 112 127]
  ...
  [ 67  79  93]
  [ 63  73  90]
  [ 71  81  98]]

 [[ 94 109 125]
  [ 96 111 127]
  [ 93 110 126]
  ...
  [ 71  82  96]
  [ 71  82  96]
  [ 67  79  93]]

 ...

 [[110 108 108]
  [114 111 112]
  [115 113 113]
  ...
  [108 106  97]
  [107 107  93]
  [110 110  96]]

 [[106 106 106]
  [106 106 106]
  [107 107 107]
  ...
  [107 104  98]
  [107 105  96]
  [104 103  94]]

 [[106 106 106]
  [102 102 102]
  [104 104 104]
  ...
  [ 98  96  90]
  [ 98  97  88]
  [ 93  91  82]]]
True
[[[ 76  95 108]
  [ 81 100 113]
  [ 83  99 113]
  ...
  [ 55  67  74]
  [ 52  63  70]
  [ 51  62  69]]

 [[ 81 100 113]
  [ 80  98 111]
  [ 79  95 108]
  ...
  [ 58  69  76]
  [ 55  67  74]
  [ 54  65  73]]

 [[ 85 101 115]
  [ 76  92 106]
  [ 74  90 103]
  ...
  [ 55  67  74]
  [ 57  69  73]
  [ 53  65  70]]

 ...

 [[ 98  96  94]
  [ 95  94  92]
  [105 103

True
[[[ 77  93 107]
  [ 75  91 104]
  [ 74  87 101]
  ...
  [ 55  57  70]
  [ 58  58  70]
  [ 59  60  71]]

 [[ 75  91 104]
  [ 74  90 103]
  [ 76  89 103]
  ...
  [ 52  55  68]
  [ 60  61  72]
  [ 60  61  72]]

 [[ 72  90 103]
  [ 72  90 103]
  [ 73  89 102]
  ...
  [ 50  54  69]
  [ 55  56  72]
  [ 61  63  79]]

 ...

 [[ 92  91  86]
  [ 95  94  90]
  [ 98  97  92]
  ...
  [ 91  87  79]
  [ 91  89  75]
  [ 91  89  75]]

 [[ 95  93  93]
  [ 92  89  90]
  [ 93  90  91]
  ...
  [ 82  83  74]
  [ 82  85  71]
  [ 82  85  71]]

 [[ 95  93  93]
  [ 88  86  86]
  [ 87  85  85]
  ...
  [ 56  56  47]
  [ 57  59  45]
  [ 56  58  44]]]
True
[[[66 77 92]
  [64 75 89]
  [65 79 93]
  ...
  [36 39 50]
  [34 42 52]
  [40 48 58]]

 [[64 75 89]
  [63 74 88]
  [64 78 92]
  ...
  [34 37 48]
  [28 36 46]
  [33 41 51]]

 [[64 75 89]
  [63 74 88]
  [64 78 92]
  ...
  [41 45 53]
  [39 48 55]
  [40 49 56]]

 ...

 [[86 83 84]
  [80 78 78]
  [82 80 80]
  ...
  [79 81 69]
  [73 76 61]
  [72 74 60]]

 [[73 73 7

True
[[[51 62 76]
  [46 58 72]
  [43 56 65]
  ...
  [24 29 35]
  [30 35 41]
  [32 37 43]]

 [[50 61 75]
  [46 58 72]
  [45 58 67]
  ...
  [24 29 35]
  [30 35 41]
  [32 37 43]]

 [[48 60 71]
  [44 56 68]
  [46 59 69]
  ...
  [27 31 37]
  [32 37 43]
  [36 41 47]]

 ...

 [[73 70 80]
  [77 74 83]
  [68 64 74]
  ...
  [59 56 50]
  [57 57 50]
  [51 51 44]]

 [[61 59 71]
  [67 65 77]
  [66 64 76]
  ...
  [51 52 43]
  [41 44 34]
  [36 39 30]]

 [[61 59 71]
  [62 60 72]
  [61 59 71]
  ...
  [39 40 31]
  [33 36 26]
  [37 41 31]]]
True
[[[59 70 86]
  [48 58 75]
  [43 54 68]
  ...
  [27 32 43]
  [28 34 44]
  [29 35 45]]

 [[48 58 75]
  [48 58 75]
  [46 58 72]
  ...
  [21 27 37]
  [27 32 43]
  [28 34 44]]

 [[41 50 69]
  [46 56 75]
  [49 59 76]
  ...
  [25 30 41]
  [32 37 48]
  [29 35 45]]

 ...

 [[63 58 61]
  [66 60 63]
  [70 71 68]
  ...
  [53 55 43]
  [56 56 49]
  [51 51 44]]

 [[61 56 66]
  [67 62 72]
  [69 71 71]
  ...
  [51 53 48]
  [54 54 54]
  [44 44 44]]

 [[61 56 66]
  [66 60 70]
  [68 

True
[[[48 59 73]
  [46 58 72]
  [36 47 61]
  ...
  [29 36 42]
  [28 38 43]
  [30 39 44]]

 [[49 60 74]
  [45 56 71]
  [43 54 68]
  ...
  [30 38 43]
  [27 37 42]
  [30 39 44]]

 [[38 49 64]
  [42 53 67]
  [53 65 79]
  ...
  [29 36 42]
  [28 38 43]
  [28 38 43]]

 ...

 [[73 71 71]
  [77 74 75]
  [78 74 79]
  ...
  [58 56 56]
  [57 55 53]
  [58 56 54]]

 [[63 62 64]
  [63 62 64]
  [68 65 72]
  ...
  [57 57 57]
  [56 56 56]
  [56 56 56]]

 [[63 62 64]
  [61 60 62]
  [63 60 68]
  ...
  [50 50 50]
  [51 51 51]
  [42 42 42]]]
True
[[[45 56 71]
  [44 55 69]
  [48 59 73]
  ...
  [29 34 47]
  [28 33 46]
  [32 36 49]]

 [[49 60 74]
  [48 59 73]
  [44 55 69]
  ...
  [30 35 48]
  [33 37 50]
  [35 40 53]]

 [[45 56 71]
  [45 56 71]
  [48 59 73]
  ...
  [34 39 50]
  [36 41 54]
  [39 43 56]]

 ...

 [[63 61 66]
  [65 64 68]
  [69 67 72]
  ...
  [43 44 42]
  [58 59 57]
  [55 56 53]]

 [[61 58 65]
  [59 57 64]
  [58 56 63]
  ...
  [45 47 47]
  [52 54 54]
  [46 48 48]]

 [[57 55 62]
  [55 52 60]
  [51 

<function destroyAllWindows>