# The Python Mega Course: Build 10 Real World Applications
---

This notebook contains the source code for the video lectures of Section 7 of [The Python Mega Course: Build 10 Real World Applciations](https://www.udemy.com/the-python-mega-course/?couponCode=GITHEADSECTION).

# Section 7: Numpy
***

**Lecture 105:** [What is Numpy](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5163296?start=0)
---

NumPy is the fundamental package for scientific computing with Python. It provides a way to store and manipulate big arrays of numeric values in a more efficient way than standard Python lists. Libraries such as pandas or opencv are based on numpy. 

The central object of numpy is the numpy array. Here's an example of how to create a numpy array:

In [2]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
#you can change its structure
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
#another way to create a numpy array is from Python lists
m = numpy.asarray([[12,13],[14,15],[16,17]])
m

array([[12, 13],
       [14, 15],
       [16, 17]])

**Lecture 106:** [Installing the OpenCV Library](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5940430?start=0)
---

The next lecture covers opencv - an image processing library that is based on numpy. To install it:

In [ ]:
pip install opencv-python

If that doesn't work on Mac, try brew install opencv

**Lecture 107:** [Imagex to Numpy and Vice-versa](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5941086?start=0)
---

For this section you will need an image file. [In this link](http://pythonhow.com/data/python-mega-course-data/section_numpy/smallgray.png) you can get a small image file. Once you open the link in your browser, right click and go to *Save Page* as to save it as an image and put it in the same folder with this script.

In [11]:
#import opencv
import cv2

In [13]:
#convert the grayscale version of the image to a numpy array
im_g = cv2.imread("smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [15]:
#convert BGR (color) version the image to a numpy array
im_g = cv2.imread("smallgray.png", 2)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
#convert a numpy array into an image
cv2.imwrite("newsmallgray.png", im_g)

True

There should be a newsmallgray.png file in your current directory now.

**Lecture 108:** [Indexing, Slicing, and Iterating](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5163302?start=0)
---

Lets suppose we have the following numpy array:

In [17]:
im_g = cv2.imread("smallgray.png", 2)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
#intersection of rows with index 0 to 1 and columns with index 2 to 3
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [23]:
#intersection of all rows with columns with index 2 to 3
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [24]:
#cell with row index 2 and column index 4
im_g[2,4]

182

In [25]:
#looping over the array rows
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [26]:
#looping over the array columns
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [27]:
#looping over the array cells
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


**Lecture 109:** [Stacking and Splitting](https://www.udemy.com/the-python-mega-course/learn/v4/t/lecture/5163304?start=0)
---

Lets again suppose we have the following numpy array:

In [29]:
im_g = cv2.imread("smallgray.png", 2)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
#stacking three arrays horizontally
ims = numpy.hstack((im_g, im_g, im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [32]:
#stacking three arrays vertically
ims = numpy.vstack((im_g, im_g, im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [33]:
#splitting horizontally into 5 numpy arrays
lst = numpy.hsplit(ims, 5)
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [34]:
#splitting vertically into 3 numpy arrays
lst = numpy.vsplit(ims, 3)
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [35]:
#access the first array of the big numpy array
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)